gnome-terminal -- bash -c "ros2 run tts_package service"
gnome-terminal -- bash -c "ros2 run speech_recognizer speech_recognizer_node --ros-args -r __ns:=/speech_recognizer"
gnome-terminal -- bash -c "ros2 run qabot client --ros-args -r __ns:=/chatbot"
gnome-terminal -- bash -c "ros2 run hand_gestures hand_gestures_node"
gnome-terminal -- bash -c "python3 client/unified_arms_client.py"
gnome-terminal -- bash -c "ros2 launch face_tracker face_tracker.test.launch.py"
gnome-terminal -- bash -c "ros2 run full_demo full_demo_node"