#!/usr/bin/bash
# Start main robot script
gnome-terminal --tab -- bash -c "ros2 launch robot robot.fake.launch.py; exec bash"
# Give the robot time to load up the controllers and such before continuing
sleep 5
# Launch face tracker and tracking preview window
gnome-terminal --tab -- bash -c "ros2 run rqt_image_view rqt_image_view /face_tracker/image_face & ros2 launch face_tracker face_tracker.test.launch.py; exec bash"
# Launch other ros2 nodes
gnome-terminal --tab -- bash -c "ros2 run face_tracker_movement face_tracker_movement_node --ros-args -p simulation:=true ; exec bash"
