#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from pydub import AudioSegment
import os

aalto_aanne = {
"vokaali" : {
	"a": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/a.wav')),
	"e": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/e.wav')),
	"i": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/i.wav')),
	"o": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/o.wav')),
	"u": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/u.wav')),
	"y": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/y.wav')),
	"å": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/o.wav')),
	"ä": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/ä.wav')),
	"ö": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/ö.wav'))
	},
"konsonantti" :{
	"b": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/b.wav')),
	"c": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/k.wav')), #c_k
	"d": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/d.wav')),
	"f": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/f.wav')),
	"g": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/g.wav')),
	"h": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/h.wav')),
	"j": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/j.wav')),
	"k": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/k.wav')),
	"l": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/l2.wav')),
	"m": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/m.wav')),
	"n": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/n.wav')),
	"p": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/p.wav')),
	"q": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/q.wav')),
	"r": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/r.wav')),
	"s": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/s.wav')),
	"t": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/t.wav')),
	"v": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/v.wav')),
	"w": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/v.wav')),
	"x": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/x.wav')),
	"z": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/z.wav')),
	" ": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/blank2.wav')),
	".": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak/puols.wav')),
	",": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak/puols.wav')),
	";": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak/puols.wav')),
	":": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak/puols.wav')),
	"ng": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak/-ng-ng.wav'))
	},
"diftongi" : {                                         #uusi, diftongit
	"ae": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ae.wav")),
	"ai": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ai.wav")),
	"ao": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ao.wav")),
	"au": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/au.wav")),
	"ay": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ay.wav")),
	"aä": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/aä.wav")),
	"aö": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/aö.wav")),
    
        "ea": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ea.wav")),
	"ei": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ei.wav")),
	"eo": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/eo.wav")),
	"eu": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/eu.wav")),
	"ey": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ey.wav")),
	"eä": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/eä.wav")),
	"eö": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/eö.wav")),
    
        "ia": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ia.wav")),
	"ie": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ie.wav")),
	"io": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/io.wav")),
	"iu": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/iu.wav")),
	"iy": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/iy.wav")),
	"iä": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/iä.wav")),
	"iö": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/iö.wav")),
    
        "oa": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/oa.wav")),
	"oe": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/oe.wav")),
	"oi": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/oi.wav")),
	"ou": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ou.wav")),
	"oy": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/oy.wav")),
	"oä": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/oä.wav")),
	#"oö": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__)"skpeak2/oö.wav")),
    
        "ua": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ua.wav")),
	"ue": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ue.wav")),
	"ui": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ui.wav")),
	"uo": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/uo.wav")),
	"uy": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/uy.wav")),
	"uä": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/uä.wav")),
	"uö": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/uö.wav")),
    
        "ya": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ya.wav")),
	"ye": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/ye.wav")),
	"yi": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/yi.wav")),
	"yo": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/yo.wav")),
	"yu": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/yu.wav")),
	"yä": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/yä.wav")),
	"yö": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/yö.wav")),
    
        "äa": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/äa.wav")),
	"äe": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/äe.wav")),
	"äi": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/äi.wav")),
	"äo": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/äo.wav")),
	"äu": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/äu.wav")),
	"äy": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/äy.wav")),
	"äö": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/äö.wav")),
    
        "öa": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/öa.wav")),
	"öe": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/öe.wav")),
	"öi": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/öi.wav")),
	"öo": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/öo.wav")),
	#"öu": AudioSegment.from_wav("skpeak2/öu.wav"),
	"öy": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/öy.wav")),
	"öä": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__),"skpeak2/öä.wav"))
	},
"aakkoset" : {
	"aa": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/aa.wav')),
	#"bb": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/bb.wav')),
	#"cc": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/cc.wav')), 
	#"dd": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/dd.wav')),
	"ee": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/ee.wav')),
	#"ff": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/ff.wav')),
	#"gg": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/gg.wav')),
	#"hh": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/hh.wav')),
	"ii": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/ii.wav')),
	#"jj": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/jj.wav')),
	#"kk": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/kk.wav')),
	#"ll": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/ll.wav')),
	#"mm": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/mm.wav')),
	#"nn": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/nn.wav')),
	"oo": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/oo.wav')),
	#"pp": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/pp.wav')),
	#"qq": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/qq.wav')),
	#"rr": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/rr.wav')),
	#"ss": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/ss.wav')),
	#"tt": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/tt.wav')),
	"uu": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/uu.wav')),
	#"vv": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/vv.wav')),
	#"ww": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/vv.wav')),
	#"xx": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/xx.wav')),
	"yy": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/yy.wav')),
	#"zz": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/zz.wav')),
	"åå": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/oo.wav')),
	"ää": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/ää.wav')),
	"öö": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak2/öö.wav')),
	"  ": AudioSegment.from_wav(os.path.join(os.path.dirname(__file__), 'skpeak/kohinaa.wav'))
	}
}
