---
- name: Create folder for ros2_control workspace
  become: true
  ansible.builtin.file:
    path: /home/{{ ansible_env.USER }}/ros2_control_ws/src
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0755"

- name: Import repositories via vcs
  ansible.builtin.shell: vcs import src < /home/{{ ansible_env.USER }}/SOP-Robot/ansible-scripts/ros2_control_ws.repos.yml
  args:
    chdir: /home/{{ ansible_env.USER }}/ros2_control_ws/

- name: Remove tricycle_controller directory if present
  ansible.builtin.file:
    path: /home/{{ ansible_env.USER }}/ros2_control_ws/src/ros-controls/ros2_controllers/tricycle_controller
    state: absent

- name: Install ROS Humble dependencies from apt
  become: true
  ansible.builtin.apt:
    name:
      - ros-humble-backward-ros
      - ros-humble-generate-parameter-library
      - ros-humble-kinematics-interface
      - ros-humble-kinematics-interface-kdl
      - ros-humble-ackermann-msgs
      - ros-humble-realtime-tools
      - ros-humble-joint-trajectory-controller
    state: present
    update_cache: true

- name: Install other required system dependencies
  become: true
  ansible.builtin.apt:
    name:
      - python3-colcon-common-extensions
      - python3-vcstool
      - python3-rosdep
    state: present
    update_cache: true

- name: Initialize rosdep
  become: true
  ansible.builtin.command:
    cmd: rosdep update
    creates: /etc/ros/rosdep/sources.list.d
  ignore_errors: yes

- name: Install any missing dependencies via rosdep
  ansible.builtin.command:
    cmd: rosdep install --from-paths src --ignore-src --rosdistro humble -r -y
    chdir: /home/{{ ansible_env.USER }}/ros2_control_ws

- name: Build workspace with colcon
  ansible.builtin.shell: source /opt/ros/humble/setup.bash && colcon build --symlink-install
  args:
    chdir: /home/{{ ansible_env.USER }}/ros2_control_ws
    executable: /bin/bash

- name: Source workspace setup in .bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_env.USER }}/.bashrc
    line: source /home/{{ ansible_env.USER }}/ros2_control_ws/install/local_setup.bash
    state: present

- name: Source workspace setup for noninteractive shell
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_env.USER }}/.bashrc_noninteractive
    line: source /home/{{ ansible_env.USER }}/ros2_control_ws/install/local_setup.bash
    state: present
