---
  - name: Run rosdep install
    ansible.builtin.shell: >
      source /opt/ros/humble/setup.bash &&
      source /home/{{ ansible_env.USER }}/ros2_control_ws/install/local_setup.bash &&
      rosdep install --from-paths src --ignore-src --rosdistro humble -r -y
    args:
      chdir: /home/{{ ansible_env.USER }}/SOP-Robot
      executable: /bin/bash

  - name: Run colcon build for ~/SOP-Robot
    ansible.builtin.shell: >
      source /opt/ros/humble/setup.bash &&
      source /home/{{ ansible_env.USER }}/ros2_control_ws/install/local_setup.bash &&
      colcon build
    args:
      chdir: /home/{{ ansible_env.USER }}/SOP-Robot
      executable: /bin/bash

  - name: Source ROS setup for {{ ansible_env.USER }}
    ansible.builtin.lineinfile:
      path: /home/{{ ansible_env.USER }}/.bashrc
      line: source /home/{{ ansible_env.USER }}/SOP-Robot/install/local_setup.bash
      state: present

  - name: Source ROS setup for noninteractive bash for {{ ansible_env.USER }}
    ansible.builtin.lineinfile:
      path: /home/{{ ansible_env.USER }}/.bashrc_noninteractive
      line: source /home/{{ ansible_env.USER }}/SOP-Robot/install/local_setup.bash
      state: present