"""Canonical and compatibility topics used by the TTS package."""

from voice_stack_common.contracts import (
    ASSISTANT_TEXT_TOPIC,
    CAN_LISTEN_TOPIC,
    GLOBAL_CAN_LISTEN_TOPIC,
    JAW_TOPIC,
    LEGACY_CHATBOT_RESPONSE_TOPIC,
    STATUS_TOPIC,
    LOG_TOPIC,
    TTS_DONE_TOPIC,
)

CANONICAL_INPUT_TOPIC = ASSISTANT_TEXT_TOPIC
LEGACY_INPUT_TOPIC = LEGACY_CHATBOT_RESPONSE_TOPIC
CAN_LISTEN_OUTPUT_TOPIC = CAN_LISTEN_TOPIC
LEGACY_CAN_LISTEN_OUTPUT_TOPIC = GLOBAL_CAN_LISTEN_TOPIC
JAW_OUTPUT_TOPIC = JAW_TOPIC
STATUS_OUTPUT_TOPIC = STATUS_TOPIC
LOG_OUTPUT_TOPIC = LOG_TOPIC
TTS_DONE_OUTPUT_TOPIC = TTS_DONE_TOPIC
